branch-defaults:
  master:
    environment: production
  staging:
    environment: staging
global:
  application_name: netball
  default_ec2_keyname: realinsurance-shared
  default_platform: PHP 5.5
  default_region: eu-west-1
  profile: netball-staging
  sc: git